GET http://localhost:8001/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/user/count
Accept: application/json
#token: {{token}}

###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone": "15906278988",
  "password": "123456"
}

> {%
    client.global.set("token", response.body.data.token);
%}


###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{
  "phone": "15906278988",
  "password": "123456"
}

> {%
   client.global.set("token", response.body.data.token);
%}

###
GET http://localhost:8000/content-service/share/notice
Accept: application/json

###
GET http://localhost:8000/content-service/share/list
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/content-service/share/3
Accept: application/json
token: {{token}}

###
POST http://localhost:8000/user-service/user/updateBonus
Accept: application/json
token: {{token}}
Content-Type: application/json

{
   "userId": 1,
   "bonus": 100
}

###
POST http://localhost:8000/content-service/share/contribute
Content-Type: application/json
token: {{token}}

{
"userId": 1,
"author": "dingyihang",
"title": "SpringCloud微服务入门",
"isOriginal": 1,
"price": 200,
"downloadUrl": "https://cn.vuejs.org",
"cover": "http://niit-soft.oss-cn-hangzhou.aliyuncs.com/share-app/vue3.png",
"summary": "详解 SpringCloud, 详解 SpringCloud, 详解 SpringCloud"
}

###
GET http://localhost:8000/content-service/share/myContribute?pageNo=1&pageSize=1
Content-Type:application/json
token: {{token}}

###
GET http://localhost:8000/content-service/share/admin/list
Accept: application/json
token: {{token}}


###
POST http://localhost:8000/content-service/share/admin/audit/1854899673838546946
token: {{token}}
Content-Type: application/json
